#ifndef __PLATFORM_H__
#define __PLATFORM_H__


// config for Skylake / Kabylake iGPU
#define NUM_THREADS_PER_EU 	 	7
#define NUM_GPR_PER_EU		 	128
#define GPR_SIZE_B			 	32
#define NUM_EUS_PER_SUBSLICE 	8
#define NUM_SUBSLICE_PER_SLICE 	3
#define NUM_SLICE_GT2			1
#define NUM_SLICE_GT3			2
#define NUM_TOTAL_EUS_GT2 		( (NUM_EUS_PER_SUBSLICE) * (NUM_SUBSLICE_PER_SLICE) * (NUM_SLICE_GT2) )	// = 24
#define NUM_TOTAL_EUS_GT3 		( (NUM_EUS_PER_SUBSLICE) * (NUM_SUBSLICE_PER_SLICE) * (NUM_SLICE_GT3) )	// = 48
#define NUM_TOTAL_THREADS_GT2	( (NUM_TOTAL_EUS_GT2) * (NUM_THREADS_PER_EU) )	// = 168
#define NUM_TOTAL_THREADS_GT3	( (NUM_TOTAL_EUS_GT3) * (NUM_THREADS_PER_EU) )	// = 336

#define FLOPS_PER_CLK_HALF_PREC	768
#define FLOPS_PER_CLK_SING_PREC 384
#define FLOPS_PER_CLK_DOUB_PREC	96

// caches
#define L3_CACHE_TOTAL_SIZE_KB	768
#define L3_CACHE_NUM_BANK		4
#define L3_CACHE_BANDWIDTH_BYTES_PER_CLK	(4*64)
#define INST_CACHE_TOTAL_SIZE_KB			(3*48)

// instruction issue rates
#define ISSUE_RATE_FMAD_SP_OP_PER_EU_PER_CLK	8
#define ISSUE_RATE_FMUL_SP_OP_PER_EU_PER_CLK	8
#define ISSUE_RATE_FADD_SP_OP_PER_EU_PER_CLK	8
#define ISSUE_RATE_MIN_SP_OP_PER_EU_PER_CLK		8
#define ISSUE_RATE_MAX_SP_OP_PER_EU_PER_CLK		8
#define ISSUE_RATE_CMP_SP_OP_PER_EU_PER_CLK		8
#define ISSUE_RATE_INV_SP_OP_PER_EU_PER_CLK		2
#define ISSUE_RATE_SQRT_SP_OP_PER_EU_PER_CLK	2
#define ISSUE_RATE_RSQRT_SP_OP_PER_EU_PER_CLK	2
#define ISSUE_RATE_LOG_SP_OP_PER_EU_PER_CLK		2
#define ISSUE_RATE_EXP_SP_OP_PER_EU_PER_CLK		2
#define ISSUE_RATE_POW_SP_OP_PER_EU_PER_CLK		1
#define ISSUE_RATE_IDIV_SP_OP_PER_EU_PER_CLK	6	// 1-6
#define ISSUE_RATE_TRIG_SP_OP_PER_EU_PER_CLK	2
#define ISSUE_RATE_FDIV_OP_PER_EU_PER_CLK		1


// load/store
#define NUM_LS_DATA_PORTS		3
#define L3_LS_BYTES_PER_CLK		(3*64)
#define SLM_LS_BYTES_PER_CLK	(3*64)




#endif 
